#!/bin/bash

# Claude Toolkit MCP Setup Script
# Sets up global MCP environment variables in ~/.claude/.env
# Run this once - it will auto-load in all future terminal sessions

set -e

echo "🔧 Claude Toolkit MCP Setup"
echo "================================"
echo ""
echo "This script will configure your MCP environment variables."
echo "They will be saved globally and automatically loaded in all terminal sessions."
echo ""

# Create ~/.claude directory if it doesn't exist
mkdir -p ~/.claude

# Check if ~/.claude/.env already exists
if [ -f ~/.claude/.env ]; then
    echo "⚠️  ~/.claude/.env already exists"
    read -p "Do you want to update it? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Cancelled."
        exit 1
    fi
fi

echo ""
echo "Please enter your API keys:"
echo ""

# Linear API Key
echo "1️⃣  Linear API Key"
echo "   Get from: https://linear.app/settings/api"
read -p "   Enter your Linear API key: " LINEAR_KEY

if [ -z "$LINEAR_KEY" ]; then
    echo "   ⚠️  Skipping Linear..."
fi

echo ""

# Sentry API Key
echo "2️⃣  Sentry API Key"
echo "   Get from: https://sentry.io/settings/account/api/"
read -p "   Enter your Sentry API key: " SENTRY_KEY

if [ -z "$SENTRY_KEY" ]; then
    echo "   ⚠️  Skipping Sentry..."
fi

echo ""

# Create ~/.claude/.env file
cat > ~/.claude/.env << EOF
# MCP Environment Variables
# Generated by claude-toolkit setup.sh
# This file is sourced automatically by ~/.zshrc

LINEAR_API_KEY=$LINEAR_KEY
SENTRY_API_KEY=$SENTRY_KEY
EOF

echo "✅ Environment variables saved to ~/.claude/.env"
echo ""

# Check if ~/.zshrc exists and add source command if needed
if [ -f ~/.zshrc ]; then
    if grep -q "source ~/.claude/.env" ~/.zshrc; then
        echo "✓ ~/.zshrc already configured"
    else
        echo "source ~/.claude/.env" >> ~/.zshrc
        echo "✓ Added to ~/.zshrc"
    fi
else
    echo "source ~/.claude/.env" > ~/.zshrc
    echo "✓ Created ~/.zshrc"
fi

echo ""
echo "📝 Setup complete!"
echo ""
echo "✅ Your API keys are now available globally in all terminal sessions."
echo ""
echo "📌 Next steps:"
echo "   1. Reload your shell:"
echo "      source ~/.zshrc"
echo ""
echo "   2. Verify setup:"
echo "      echo \$LINEAR_API_KEY"
echo ""
echo "   3. Start Claude Code:"
echo "      claude"
echo ""
echo "   4. Check MCP servers:"
echo "      /mcp"
echo ""
