#!/bin/bash

# Claude Toolkit MCP Setup Script
# This script helps you configure MCP environment variables

set -e

echo "🔧 Claude Toolkit MCP Setup"
echo "================================"
echo ""

# Check if .env already exists
if [ -f ".env" ]; then
    echo "⚠️  .env file already exists"
    read -p "Do you want to overwrite it? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Cancelled."
        exit 1
    fi
fi

echo ""
echo "Please enter your API keys:"
echo ""

# Linear API Key
echo "1️⃣  Linear API Key"
echo "   Get from: https://linear.app/settings/api"
read -p "   Enter your Linear API key: " LINEAR_KEY

if [ -z "$LINEAR_KEY" ]; then
    echo "   ⚠️  Linear API key is empty, skipping..."
    LINEAR_KEY=""
fi

echo ""

# Sentry API Key
echo "2️⃣  Sentry API Key"
echo "   Get from: https://sentry.io/settings/account/api/"
read -p "   Enter your Sentry API key: " SENTRY_KEY

if [ -z "$SENTRY_KEY" ]; then
    echo "   ⚠️  Sentry API key is empty, skipping..."
    SENTRY_KEY=""
fi

echo ""

# Create .env file
cat > .env << EOF
# MCP Environment Variables
# Generated by setup.sh

LINEAR_API_KEY=$LINEAR_KEY
SENTRY_API_KEY=$SENTRY_KEY
EOF

echo "✅ Setup complete!"
echo ""
echo "📝 Created .env file with:"
if [ -n "$LINEAR_KEY" ]; then
    echo "   ✓ LINEAR_API_KEY"
fi
if [ -n "$SENTRY_KEY" ]; then
    echo "   ✓ SENTRY_API_KEY"
fi

echo ""
echo "📌 Next steps:"
echo "   1. Load environment variables:"
echo "      source .env"
echo ""
echo "   2. Start Claude Code:"
echo "      claude"
echo ""
echo "   3. Verify MCP servers:"
echo "      /mcp"
echo ""
